name: Build

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ windows-latest, ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
              with:
                submodules: recursive
                token: ${{ secrets.DISCORD_SDK_PAT }}

            - name: Setup 7-Zip
              uses: milliewalky/setup-7-zip@v2
            
            - name: Setup Linux dependencies and resources
              if: matrix.os == 'ubuntu-latest'
              shell: bash
              run: |
                # Setup Allegro, setup resource, and unzip dependency

                sudo apt-get update
                sudo apt-get install -y liballegro5-dev

                mkdir -p resources
                echo "${{ secrets.DISCORD_APP_CLIENT_ID }}" > resources/discord_app_id.txt

                chmod +x ./unzip_sdk.sh
                ./unzip_sdk.sh

            - name: Setup Windows dependencies and resources
              if: matrix.os == 'windows-latest'
              shell: pwsh
              run: |
                # Setup Allegro, setup resource, and unzip dependency

                vcpkg install allegro5:x64-windows

                New-Item -ItemType Directory -Force -Path resources
                "${{ secrets.DISCORD_APP_CLIENT_ID }}" > resources/discord_app_id.txt

                ./unzip_sdk.ps1


            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                options: |
                  ${{ matrix.os == 'windows-latest' && 'CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake' || '' }}
            
            - name: Upload build
              uses: actions/upload-artifact@v7
              with:
                name: UPLOAD_${{ matrix.os }}
                path: build/bin/executable