name: Build

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
              with:
                submodules: recursive
                token: ${{ secrets.DISCORD_SDK_PAT }}

            - name: Setup 7-Zip
              uses: milliewalky/setup-7-zip@v2
            
            - name: Setup Linux dependencies and resources
              if: matrix.os == 'ubuntu-latest'
              shell: bash
              run: |
                # Setup dependencies

                sudo apt update
                sudo apt install -y libasound2-dev libpulse-dev libaudio-dev \
                  libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev \
                  libxcursor-dev libxi-dev libxinerama-dev libxss-dev libgl1-mesa-dev \
                  libdbus-1-dev libvulkan-dev libwayland-dev libxkbcommon-dev \
                  libegl1-mesa-dev libibus-1.0-dev libusb-1.0-0-dev libxtst-dev

                mkdir -p resources
                echo "${{ secrets.DISCORD_APP_CLIENT_ID }}" > resources/discord_app_id.txt

                chmod +x ./unzip_sdk.sh
                ./unzip_sdk.sh

            - name: Setup Windows dependencies and resources
              if: matrix.os == 'windows-latest'
              shell: pwsh
              run: |
                # Setup dependencies

                New-Item -ItemType Directory -Force -Path resources
                "${{ secrets.DISCORD_APP_CLIENT_ID }}" > resources/discord_app_id.txt

                ./unzip_sdk.ps1


            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
            
            - name: Upload build
              uses: actions/upload-artifact@v7
              with:
                name: UPLOAD_${{ matrix.os }}
                path: build/bin/executable